name: run-test

on: [push, workflow_call, pull_request]
    
jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
    - name: Initialising repository
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        pip install "cglbm[develop]" .

    - name: Run tests
      run: |
        pytest